Nâng cấp module từ NukeViet 4.3.03 lên NukeViet 4.5.00
nukeviet/module-download pull request #107
Opened 2021-07-22 01:23 UTC by ngoclam99

2021-07-23 09:08 UTC, htuyen1994 commented
1. down.php k nên sử dụng $canonicalUrl = getCanonicalUrl($page_url);
vì nó là func k hiển thị, sử dụng để download file, nếu có cần kiểm tra lại $page_url vì đang lỗi

2. đoạn tích hợp recapcha đang thiếu $module_config[$module_name]['captcha_type'], cần viết đoạn config này trong module config, bên cạnh đó cần kiểm tra các đoạn hiển thị capcha và xác thực capcha tại upload.php

3. Thiếu Cấu hình bình luận sử dụng capcha

2021-07-30 04:12 UTC, hoaquynhtim99 commented on modules/download/admin/config.php
> +    $array['captcha_type_comm'] = $nv_Request->get_string('captcha_type', 'post', '');
@ngoclam99 2 line này sao lại get string em?

2021-07-30 04:12 UTC, hoaquynhtim99 commented on modules/download/admin/config.php
> +            $sth = $db->prepare('INSERT INTO ' . NV_CONFIG_GLOBALTABLE . ' (lang, module, config_name, config_name) VALUES (' . NV_LANG_DATA . ', ' . $module_name . ', :config_name, :config_value)');
@ngoclam99 lệnh này sai, insert string mà sao lại ghi `' . NV_LANG_DATA . ', ' . $module_name . '` quote cho nó đâu?

2021-07-30 04:15 UTC, hoaquynhtim99 commented on modules/download/funcs/main.php
> +            }
@ngoclam99 chỗ này là dạng xem theo thể loại, các tin khác bên dưới nó làm gì có phân trang hả em.

2021-07-30 04:18 UTC, hoaquynhtim99 commented on modules/download/funcs/rss.php
> +
@ngoclam99 chỗ RSS là chỗ không hiển thị, không cần cái này. Nếu có cũng được nhưng phải đúng. Của em đang lỗi, lỗi cho trường hợp RSS của thể loại, xem dòng `$catalias = isset($array_op[1]) ? $array_op[1] : '';` là hiểu

2021-07-30 04:21 UTC, hoaquynhtim99 commented on modules/download/funcs/search.php
>  $base_url_rewrite = $request_uri = urldecode($_SERVER['REQUEST_URI']);
@ngoclam99 dòng này không dùng đến phải xóa đi

2021-07-30 04:23 UTC, hoaquynhtim99 commented on modules/download/funcs/search.php
> +}
@ngoclam99 cách xác định này sai, chỗ này là tìm kiếm, page có dạng `&amp;page=xxx` thì làm sao lấy qua op, mà op[0] nó đã là cái search rồi

2021-07-30 04:24 UTC, hoaquynhtim99 commented on modules/download/funcs/search.php
> +}
@ngoclam99 nối $page_url thế này cũng sai, chỗ này &amp;page=xxxx mà

2021-07-30 04:24 UTC, hoaquynhtim99 commented on modules/download/funcs/search.php
> +    betweenURLs($page, ceil($num_items/$per_page), $base_url, $urlappend, $prevPage, $nextPage);
@ngoclam99 $urlappend này cũng sai luôn

2021-07-30 04:25 UTC, hoaquynhtim99 commented on modules/download/funcs/sitemap.php
> +$canonicalUrl = getCanonicalUrl($page_url);
@ngoclam99 chỗ này không dùng cái này vì là function không hiển thị, link của nó thực tế có dạng https://nukeviet.vn/sitemap-vi.download.xml khai báo như thế sẽ không xài được

2021-07-30 04:30 UTC, hoaquynhtim99 commented on modules/download/funcs/main.php
> +    }
Không cần xác định biến $page này vì nó đã được xác định tại đây https://github.com/nukeviet/module-download/blob/a709af3a3f4a3cae2df19021e5caf56060e879a8/modules/download/functions.php#L152

2021-07-30 04:36 UTC, hoaquynhtim99 requested changes

2021-07-30 04:36 UTC, hoaquynhtim99 commented on modules/download/funcs/main.php
> +    }
@ngoclam99

2021-07-30 04:36 UTC, hoaquynhtim99 commented on modules/download/funcs/viewcat.php
> +}
@ngoclam99 không cần xác định $page chỗ này vì nó đã được xác định tại đây https://github.com/nukeviet/module-download/blob/a709af3a3f4a3cae2df19021e5caf56060e879a8/modules/download/functions.php#L136

2021-07-30 04:36 UTC, hoaquynhtim99 commented on modules/download/funcs/viewcat.php
> +        $page_url .= '/page-' . $page;
@ngoclam99 chỗ này nối làm gì cái này vào nữa, bên trên nó đã nối rồi mà

2021-07-31 09:22 UTC, hoaquynhtim99 requested changes

2021-07-31 09:22 UTC, hoaquynhtim99 commented on modules/download/language/admin_vi.php
> +$lang_module['captcha_type_recaptcha_note'] = 'Captcha sẽ không chạy cho đến khi bạn <a href="%s">định cấu hình reCaptcha</a>';
@ngoclam99 modules/download/language/admin_en.php hình như chưa thêm lang

2021-07-31 10:10 UTC, merged